name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        
    - name: Grant execute permission for gradlew
      run: chmod +x ./ai-exception-insight/gradlew
      
    - name: Build with Gradle
      run: cd ai-exception-insight && ./gradlew build
      
    - name: Run tests
      run: cd ai-exception-insight && ./gradlew test
      
    - name: Generate Test Report
      run: cd ai-exception-insight && ./gradlew jacocoTestReport
      if: always()
      
  publish:
    needs: build-and-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        
    - name: Grant execute permission for gradlew
      run: chmod +x ./ai-exception-insight/gradlew
      
    - name: Publish package
      run: cd ai-exception-insight && ./gradlew publish 